 INSERT INTO currencies (country, isocode, symbol, name)
 VALUES ('Nigeria', 'NGN', '₦', 'Naira'),
     ('Ghana', 'GHS', '₵', 'Cedis'),
     ('Egypt', 'EGP', '£', 'Egyptian Pound'),
     ('Kenya', 'KES', 'Sh', 'Shillings'),
     ('China', 'CNY', '¥', 'Yuan'),
     ('Mexico', 'MXN', '$', 'Mexican Peso'),
     ('EU', 'EUR', '€', 'Euro'),
     ('Japan', 'JPY', '¥', 'Japanese Yen'),
     ('Canada', 'CAD', '$', 'Canadian Dollar'),
     ('India', 'INR', 'Rs', 'Rupee'),
     ('United Kingdom', 'GBP', '£', 'Pound'),
 ('Russia', 'RUB', '₽', 'Ruble'),
 ('Argentina', 'ARS', '$', 'Argentine Peso'),
 ('United Arab Emirates', 'AED', 'د.إ', 'Dirham'),
 ('Australia', 'AUD', '$', 'Austrialian Dollar'),
 ('Bangladesh', 'BDT', '৳', 'Bangladeshi Taka'),
 ('Bahrain', 'BHD', '.د.ب', 'Bahraini Dinar'),
 ('Bolivia', 'BOB', 'Bs', 'Bolivian boliviano'), 
 ('Brazil', 'BRL', 'R$', 'Brazilian Real'),
 ('Chile', 'CLP', '$', 'Chilean Peso'),
 ('Colombia', 'COP', '$', 'Colombia Peso'),
 ('Costa Rica', 'CRC', '₡', 'Costa Rican Colon'),
 ('Czech Republic', 'CZK', 'Kč', 'Czech Koruna'),
 ('Dominican Republic', 'DOP', 'RD$', 'Dominican Peso'),
 ('Algeria', 'DZD', 'دج', 'Algerian Dinar'),
 ('Georgia', 'GEL', 'ლ', 'Georgian Lari'),
 ('Hong Kong', 'HKD', 'HK$', 'Hong Kong Dollar'),
 ('Indonesia', 'IDR', 'Rp', 'Indonesian Rupiahs'),
 ('Cambodia', 'KHR', '៛', 'Cambodian Riel'),
 ('South Korean', 'KRW', '₩', 'South Korean Won'),
 ('Kuwait', 'KWD', 'د.ك', 'Kuwaiti Dinars'),
 ('Kazakhstan', 'KZT', '₸', 'Kazakhstani Tenge'),
 ('Laos', 'LAK', '₭N', 'Lao Kips'),
 ('Lebanon', 'LBP', 'ل.ل.', 'Lebanese pound'),
 ('Sri Lanka', 'LKR', 'රු', 'Sri Lanka Rupee'),
 ('Morocco', 'MAD', 'MAD', 'Moroccan Dirham'),
 ('Myanmar', 'MMK', 'K', 'Myanmar Kyat'),
 ('Malaysia', 'MYR', 'RM', 'Malaysian Ringgit'),
 ('Oman', 'OMR', 'ر.ع.', 'Omani Rial'),
 ('Panama', 'PAB', 'B/', ' Panamanian Balboa'),
 ('Peru', 'PEN', 'S/', 'Nuevo Sol'),
 ('Philippines', 'PHP', '₱', ' Philippine peso'),
 ('Poland', 'PLN', 'zł', 'Polish Zloty'),
 ('Paraguay', 'PYG', '₲', 'Paraguayan Guaran'),
 ('Qatar', 'QAR', 'ر.ق', 'Qatari Rial'),
 ('Romania', 'RON', 'lei', 'Romanian Leu'),
 ('Saudi Arabia', 'SAR', 'ر.س', 'Saudi Riyal'),
 ('Sudan', 'SDG', 'ج.س.', 'Sudanese Pounds '),
 ('Sweden', 'SEK', 'kr', 'Swedish Krona'),
 ('Singapore', 'SGD', 'S$', 'Singapore Dollar'),
 ('Thailand', 'THB', '฿', 'Thai Baht'),
 ('Tunisia', 'TND', 'د.ت', 'Tunisian Dinar'),
 ('Turkey', 'TRY', '₺', 'Turkish Lire'),
 ('Taiwan', 'TWD', 'NT$', 'New Taiwan Dollar'),
 ('Ukraine', 'UAH', '₴', 'Ukrainian Hryvnia'),
 ('Uganda', 'UGX', 'USH', 'Ugandan Shilling'),
 ('Uruguay', 'UYU', '$U', 'Uruguayan Peso'),
 ('Venezuela', 'VES', 'Bs', 'Venezuelan Bolívares'),
 ('Vietnam', 'VND', '₫', 'Vietnamese Dong'),
 ('South Africa', 'ZAR', 'R', 'South African Rand');