// REGISTER A USER
export const GET_TRENDING_DATA = "GET_TRENDING_DATA"

// LOGIN A USER
export const ADD_CURRENCY = "ADD_CURRENCY"
export const UPDATE_CURRENCY = "UPDATE_CURRENCY"
export const GET_CURRENCY = "GET_CURRENCY"