// REGISTER A USER
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_ERROR = "USER_REGISTER_ERROR"

// LOGIN A USER
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR"
export const USER_LOGOUT = "USER_LOGOUT"

// GET A USER
export const GET_USER_REQUEST = "GET_USER_REQUEST"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_ERROR = "GET_USER_ERROR"

// USER UTILITY TYPES
export const CLEAR_USER_ERRORS = "CLEAR_USER_ERRORS"
export const CLEAR_USER_MESSAGES = "CLEAR_USER_MESSAGES"