"""Update complaints and contact tables

Revision ID: 0644a429e056
Revises: 1647257e7c03
Create Date: 2022-12-03 11:24:14.643290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0644a429e056'
down_revision = '1647257e7c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_complaints_full_name', table_name='complaints')
    op.create_index(op.f('ix_complaints_full_name'), 'complaints', ['full_name'], unique=False)
    op.add_column('contacts', sa.Column('status', sa.Enum('resolved', 'unresolved', 'in_review', name='status'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'status')
    op.drop_index(op.f('ix_complaints_full_name'), table_name='complaints')
    op.create_index('ix_complaints_full_name', 'complaints', ['full_name'], unique=False)
    # ### end Alembic commands ###