"""new complaints table

Revision ID: 11c57ee37fff
Revises: 5110fb9337e5
Create Date: 2022-11-29 18:40:24.881705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c57ee37fff'
down_revision = '5110fb9337e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
