"""migrate database

Revision ID: 1824c2625fcf
Revises: b8f4b3ffa90c
Create Date: 2022-12-01 21:29:49.044217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1824c2625fcf'
down_revision = 'b8f4b3ffa90c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
