"""updated status column

Revision ID: 50c78c20e4c5
Revises: b46b2f2c8062
Create Date: 2022-12-01 23:40:42.980658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c78c20e4c5'
down_revision = 'b46b2f2c8062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaints', 'status',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.Enum('resolved', 'unresolved', 'in_review', name='status'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaints', 'status',
               existing_type=sa.Enum('resolved', 'unresolved', 'in_review', name='status'),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    # ### end Alembic commands ###
