"""Update adverts table

Revision ID: 635d7446a57d
Revises: 8bc6c574e9f1
Create Date: 2022-12-05 11:08:17.186772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635d7446a57d'
down_revision = '8bc6c574e9f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_advert_email', table_name='advert')
    op.create_index(op.f('ix_advert_email'), 'advert', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advert_email'), table_name='advert')
    op.create_index('ix_advert_email', 'advert', ['email'], unique=False)
    # ### end Alembic commands ###