"""resolving mapper error

Revision ID: 8361187738f3
Revises: d27e22ac3508
Create Date: 2022-12-03 15:30:34.029104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8361187738f3'
down_revision = 'd27e22ac3508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###