"""initial migration

Revision ID: 8bc6c574e9f1
Revises: d27e22ac3508
Create Date: 2022-12-05 00:00:20.390892

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '8bc6c574e9f1'
# down_revision = 'd27e22ac3508'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advert',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sqlalchemy_utils.types.email.EmailType(
                        length=255), nullable=True),
                    sa.Column('pixel_size', sa.String(
                        length=100), nullable=False),
                    sa.Column('number_of_impressions', sa.String(
                        length=200), nullable=False),
                    sa.Column('ref_number', sa.Integer(), nullable=True),
                    sa.Column('link_to_banner_image', sa.String(
                        length=500), nullable=False),
                    sa.Column('timestamp', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_advert_email'), 'advert', ['email'], unique=True)
    op.create_index(op.f('ix_advert_id'), 'advert', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advert_id'), table_name='advert')
    op.drop_index(op.f('ix_advert_email'), table_name='advert')
    op.drop_table('advert')
    # ### end Alembic commands ###
