"""updated status column

Revision ID: 9198686a4df8
Revises: b9bf908c891d
Create Date: 2022-12-02 08:17:37.060774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9198686a4df8'
down_revision = 'b9bf908c891d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('status', sa.Enum('resolved', 'unresolved', 'in_review', name='status'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'status')
    # ### end Alembic commands ###