"""faq table

Revision ID: 99e8c436ffa8
Revises: 4edab9586fd5
Create Date: 2022-11-30 01:30:12.100206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e8c436ffa8'
down_revision = '4edab9586fd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_id'), 'faq', ['id'], unique=False)
    op.create_index(op.f('ix_faq_title'), 'faq', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faq_title'), table_name='faq')
    op.drop_index(op.f('ix_faq_id'), table_name='faq')
    op.drop_table('faq')
    # ### end Alembic commands ###
