"""new complaints table

Revision ID: a3107f0507a8
Revises: 11c57ee37fff
Create Date: 2022-11-29 19:09:33.741589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3107f0507a8'
down_revision = '11c57ee37fff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
