"""complaints table

Revision ID: b46b2f2c8062
Revises: 1824c2625fcf
Create Date: 2022-12-01 21:35:29.918278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b46b2f2c8062'
down_revision = '1824c2625fcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('status', sa.Enum('Resolved', 'Unresolved', 'Still_in_review', name='status'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'status')
    # ### end Alembic commands ###
