"""updated status column

Revision ID: c9a1db6b6b5d
Revises: e5a036a32617
Create Date: 2022-12-02 08:46:23.474332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9a1db6b6b5d'
down_revision = 'e5a036a32617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###