"""update complaints table

Revision ID: cb2aa9d8e7cb
Revises: 2ca6a9ddb60f
Create Date: 2022-12-01 16:39:41.131022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb2aa9d8e7cb'
down_revision = '2ca6a9ddb60f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('status', sa.Enum('Resolved', 'Unresolved', 'Still_in_review', name='status'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'status')
    # ### end Alembic commands ###
