"""sqlite migration

Revision ID: d23aafba9597
Revises: 1647257e7c03
Create Date: 2022-12-03 13:14:37.424040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd23aafba9597'
down_revision = '1647257e7c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###