"""updated status column

Revision ID: e5a036a32617
Revises: 9198686a4df8
Create Date: 2022-12-02 08:45:17.614488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5a036a32617'
down_revision = '9198686a4df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###