"""initialise

Revision ID: eaae517c1e2f
Revises:
Create Date: 2020-10-01 12:32:07.701738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaae517c1e2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic
    op.create_table('currencies',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('country', sa.String(), nullable=False),
                    sa.Column('isocode', sa.String(), nullable=False),
                    sa.Column('symbol', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('id'), 'currencies', ['id'], unique=True)
    # ### end Alembic commands ###


    op.create_table('rates',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('official_buy', sa.Float(), nullable=False),
                    sa.Column('official_sell', sa.Float(), nullable=False),
                    sa.Column('parallel_buy', sa.Float(), nullable=False),
                    sa.Column('parallel_sell', sa.Float(), nullable=False),
                    sa.Column('last_updated', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.ForeignKeyConstraint(
                        'country_id', 'currencies.id', ondelete='CASCADE'),
                    )
    op.create_index(op.f('id'), 'rates', ['id'], unique=True)

    # ### commands auto generated by Alembic
    op.create_table('admins',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('id'), 'admins', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('id'), table_name='currencies')
    op.drop_table('currencies')
    # ### end Alembic commands ###

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('id'), table_name='rates')
    op.drop_table('rates')
    # ### end Alembic commands ###

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('id'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###


# def upgrade_rates():
#     # ### commands auto generated by Alembic
#     op.create_table('rates',
#                     sa.Column('id', sa.Integer(), nullable=False),
#                     sa.Column('official_buy', sa.Float(), nullable=False),
#                     sa.Column('official_sell', sa.Float(), nullable=False),
#                     sa.Column('parallel_buy', sa.Float(), nullable=False),
#                     sa.Column('parallel_sell', sa.Float(), nullable=False),
#                     sa.Column('last_updated', sa.DateTime(), nullable=False),
#                     sa.PrimaryKeyConstraint('id'),
#                     sa.ForeignKeyConstraint(
#                         'country_id', 'currencies.id', ondelete='CASCADE'),
#                     )
#     op.create_index(op.f('id'), 'rates', ['id'], unique=True)
    # ### end Alembic commands ###


# def downgrade_rates():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_index(op.f('id'), table_name='rates')
#     op.drop_table('rates')
#     # ### end Alembic commands ###


# def upgrade_admins():
#     # ### commands auto generated by Alembic
#     op.create_table('admins',
#                     sa.Column('id', sa.Integer(), nullable=False),
#                     sa.Column('password', sa.String(), nullable=False),
#                     sa.Column('is_active', sa.Boolean(), nullable=False),
#                     sa.PrimaryKeyConstraint('id')
#                     )
#     op.create_index(op.f('id'), 'admins', ['id'], unique=False)
#     # ### end Alembic commands ###


# def downgrade_admins():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_index(op.f('id'), table_name='admins')
#     op.drop_table('admins')
#     # ### end Alembic commands ###
